print("intorudce A")
	A = int(input("A"))
	print("introduce B")
	B = int(input("B"))
	print(" A vale ", A," y B vale",B,)
print("segundo ejercicio:")
	print("la suma vale:", A + B,)
	print("la resta vale:" A - B)
	print("la multiplicación vale:" A * B)
	print("la multiplicación vale:" A / B)
