import img from "./bola-de-fuego.png";
export const filas = [{
    producto: "manzana",
    cantidad: 2,
    precio: 3.4,
    tienda: "Mercadona",
    notas: "compra 3",
    comprado: true,
    imagen: img,
},
{
    producto: "leche",
    cantidad: 8,
    precio: 4,
    tienda: "Mercadona",
    notas: "desnatada",
    comprado: false,
    imagen: img,
},
{
    producto: "galletas",
    cantidad: 1,
    precio: 2,
    tienda: "Mercadona",
    notas: "oreo",
    comprado: true,
    imagen: img,
},
{
    producto: "carne picada",
    cantidad: 5,
    precio: 6,
    tienda: "Mercadona",
    notas: "1 kg",
    comprado: false,
    imagen: img,
},
{
    producto: "queso",
    cantidad: 12,
    precio: 2,
    tienda: "Mercadona",
    notas: "light",
    comprado: true,
    imagen: img,
},
]