/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appArrayRetornaPrimer(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);
        int[] listaNull = {};
        App miarrayNull = new App(listaNull);
        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(1, miarray.retornarPrimer());
        assertEquals(0, miarrayNull.retornarPrimer());
        assertEquals(0, miarrayNull2.retornarPrimer());
    }

    @Test void appArrayRetornaDarrer(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);
        int[] listaNull = {};
        App miarrayNull = new App(listaNull);
        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(4, miarray.retornarDarrer());
        assertEquals(0, miarrayNull.retornarDarrer());
        assertEquals(0, miarrayNull2.retornarDarrer());
    }
    @Test void appArrayRetornaTercer(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);
        int[] lista2 = {1,2};
        App miarray2 = new App(lista2);
        int[] listaNull = {};
        App miarrayNull = new App(listaNull);
        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(3, miarray.retornarTercer());
        assertEquals(0, miarray2.retornarTercer());
        assertEquals(0, miarrayNull.retornarTercer());
        assertEquals(0, miarrayNull2.retornarTercer());
    }
    @Test void appArraycontar(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);
        int[] listaNull = {};
        App miarrayNull = new App(listaNull);
        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(4, miarray.contarElements());
        assertEquals(0, miarrayNull.contarElements());
        assertEquals(0, miarrayNull2.contarElements());
    }
    @Test void appArraymitjanaElements(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);
        int[] lista2 = {-1,-2,3,4};
        App miarray2 = new App(lista2);
        int[] listaNull = {};
        App miarrayNull = new App(listaNull);
        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(2.5, miarray.mitjanaElements());
        assertEquals(1, miarray2.mitjanaElements());
        assertEquals(0, miarrayNull.mitjanaElements());
        assertEquals(0, miarrayNull2.mitjanaElements());
    }
    @Test void appArraysumarElements(){
        int[] lista = {1,2,3,4};
        App miarray = new App(lista);

        int[] lista2 = {-1,-2,3,4};
        App miarray2 = new App(lista2);

        int[] listaNull = {};
        App miarrayNull = new App(listaNull);

        int[] listaNull2 = null;
        App miarrayNull2 = new App(listaNull2);
        
        assertEquals(10, miarray.sumarElements());
        assertEquals(4, miarray2.sumarElements());
        assertEquals(0, miarrayNull.sumarElements());
        assertEquals(0, miarrayNull2.sumarElements());
    }
    
}
